apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: html-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sethubrown/gitops-html-app.git
    targetRevision: HEAD
    path: app/helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
